export interface StorageBoxMount {
  login: string;       // e.g. "u123456"
  server: string;      // e.g. "u123456.your-storagebox.de"
  password: string;
  mountName: string;   // name under /mnt/, e.g. "backups"
}

/**
 * Injects CIFS Storage Box mount configuration into an existing cloud-init string.
 * Uses a credentials file (/etc/cifs-credentials/<login>) with 0600 permissions
 * rather than embedding credentials directly in fstab.
 *
 * Handles merging into existing packages/write_files/mounts/runcmd sections.
 */
export function injectStorageBoxMounts(cloudInit: string, mounts: StorageBoxMount[]): string {
  if (mounts.length === 0) return cloudInit;

  let content = cloudInit?.trim() ?? '';
  if (!content) {
    content = '#cloud-config';
  }
  if (!content.startsWith('#cloud-config')) {
    content = `#cloud-config\n${content}`;
  }

  // packages: cifs-utils
  const pkgEntries = ['  - cifs-utils'];
  content = injectItems(content, 'packages', pkgEntries, (existing) =>
    existing.includes('cifs-utils') ? [] : pkgEntries
  );

  // write_files: one credentials file per box
  const writeEntries = mounts.flatMap((m) => [
    `  - path: /etc/cifs-credentials/${m.login}`,
    `    permissions: '0600'`,
    `    content: |`,
    `      username=${m.login}`,
    `      password=${m.password}`,
  ]);
  content = injectItems(content, 'write_files', writeEntries);

  // mounts: one fstab entry per box
  const mountEntries = mounts.map(
    (m) =>
      `  - ["//${m.server}/backup", "/mnt/${m.mountName}", "cifs", ` +
      `"credentials=/etc/cifs-credentials/${m.login},iocharset=utf8,rw,noperm,_netdev", "0", "0"]`
  );
  content = injectItems(content, 'mounts', mountEntries);

  // runcmd: mkdir for credentials dir + each mount point
  const runcmdEntries = [
    '  - mkdir -p /etc/cifs-credentials',
    '  - chmod 700 /etc/cifs-credentials',
    ...mounts.map((m) => `  - mkdir -p /mnt/${m.mountName}`),
  ];
  content = injectItems(content, 'runcmd', runcmdEntries);

  return content;
}

/**
 * Appends items to a YAML list section. If the section does not exist, creates it.
 * An optional filter function can derive the entries to actually insert based on
 * existing section content (used to avoid duplicate package entries).
 */
function injectItems(
  yaml: string,
  sectionKey: string,
  entries: string[],
  filter?: (sectionContent: string) => string[]
): string {
  const toInsert = filter ? filter(yaml) : entries;
  if (toInsert.length === 0) return yaml;

  // Regex to find "sectionKey:" as a standalone key at line start
  const sectionRegex = new RegExp(`^${sectionKey}:\\s*$`, 'm');
  if (sectionRegex.test(yaml)) {
    const lines = yaml.split('\n');
    const sectionIdx = lines.findIndex((l) => new RegExp(`^${sectionKey}:\\s*$`).test(l));
    if (sectionIdx === -1) {
      return `${yaml.trimEnd()}\n${sectionKey}:\n${toInsert.join('\n')}`;
    }
    // Scan past all indented lines to find where the section ends
    let insertIdx = sectionIdx + 1;
    while (insertIdx < lines.length && /^\s/.test(lines[insertIdx])) {
      insertIdx++;
    }
    lines.splice(insertIdx, 0, ...toInsert);
    return lines.join('\n');
  }

  // Section absent — append it
  return `${yaml.trimEnd()}\n${sectionKey}:\n${toInsert.join('\n')}`;
}

/**
 * Generates a standalone bash script suitable for mounting Storage Boxes
 * on an already-running server via SSH.
 */
export function generateMountScript(mounts: StorageBoxMount[]): string {
  if (mounts.length === 0) return '';

  const lines = [
    '#!/bin/bash',
    '# Hetzner Storage Box mount script — generated by Hetzner Cloud Toolkit',
    '# Run as root on the target server.',
    'set -e',
    '',
    'echo "Installing cifs-utils..."',
    'apt-get update -qq && apt-get install -y cifs-utils',
    '',
    'echo "Setting up credentials directory..."',
    'mkdir -p /etc/cifs-credentials',
    'chmod 700 /etc/cifs-credentials',
    '',
  ];

  for (const m of mounts) {
    lines.push(
      `# ── Storage Box: ${m.login} → /mnt/${m.mountName}`,
      `printf 'username=%s\\npassword=%s\\n' '${m.login}' '${m.password}' \\`,
      `  > /etc/cifs-credentials/${m.login}`,
      `chmod 600 /etc/cifs-credentials/${m.login}`,
      `mkdir -p /mnt/${m.mountName}`,
      `mount -t cifs //${m.server}/backup /mnt/${m.mountName} \\`,
      `  -o credentials=/etc/cifs-credentials/${m.login},iocharset=utf8,rw,noperm,_netdev`,
      `# Persist in fstab`,
      `grep -q '${m.server}' /etc/fstab || \\`,
      `  echo "//${m.server}/backup /mnt/${m.mountName} cifs credentials=/etc/cifs-credentials/${m.login},iocharset=utf8,rw,noperm,_netdev 0 0" >> /etc/fstab`,
      `echo "Mounted Storage Box '${m.login}' at /mnt/${m.mountName}"`,
      '',
    );
  }

  lines.push('echo "All Storage Boxes mounted successfully."');
  return lines.join('\n');
}
